"""fix stars for hotel

Revision ID: 18e4d99d406a
Revises: f78daf91efab
Create Date: 2024-07-13 03:06:40.513537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18e4d99d406a'
down_revision = 'f78daf91efab'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hotel', 'stars')
    op.add_column('hotel', sa.Column('stars', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hotel', 'stars')
    op.add_column('hotel', sa.Column('stars', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###
