"""

Revision ID: 228cd8af9e29
Revises: fdb9980784b2
Create Date: 2024-07-19 12:14:25.686624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '228cd8af9e29'
down_revision = 'fdb9980784b2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
