"""

Revision ID: 75ce79385f1a
Revises: 228cd8af9e29
Create Date: 2024-07-19 12:19:11.484999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75ce79385f1a'
down_revision = '228cd8af9e29'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
