"""

Revision ID: 9c1b29fa3a74
Revises: b0456ed4f2dc
Create Date: 2024-07-19 12:05:31.593061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c1b29fa3a74'
down_revision = 'b0456ed4f2dc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
