"""

Revision ID: b0456ed4f2dc
Revises: 18e4d99d406a
Create Date: 2024-07-19 12:03:02.488930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0456ed4f2dc'
down_revision = '18e4d99d406a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paxa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('paxa')
    # ### end Alembic commands ###
