"""

Revision ID: b0d5b556e837
Revises: 9c1b29fa3a74
Create Date: 2024-07-19 12:06:12.719786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0d5b556e837'
down_revision = '9c1b29fa3a74'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('paxa')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paxa',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name='paxa_pkey')
    )
    # ### end Alembic commands ###
